package common;

import java.io.Serializable;

public enum MessageType implements Serializable {
    LOGIN, REGISTER, LOGOUT,
    CREATE_AUCTION, GET_AUCTIONS, UPDATE_AUCTION, DELETE_AUCTION, GET_AUCTION_DETAIL,
    GET_SELLER_AUCTIONS,
    CREATE_SELLER_ITEM,
    UPDATE_SELLER_ITEM,
    DELETE_SELLER_ITEM,
    PLACE_BID, GET_BID_HISTORY,
    UPGRADE_SELLER,
    GET_ALL_USERS, BAN_USER, DELETE_AUCTION_ADMIN,
    SUCCESS, ERROR, UPDATE, NOTIFICATION, OUTBID_NOTIFICATION,
    AUCTION_FINISHED_NOTIFICATION, AUCTION_EXTENDED_NOTIFICATION,
    UPDATE_PRICE_REALTIME,
    ADD_FUNDS,      // ← THÊM: Nạp tiền
    WITHDRAW,       // ← THÊM: Rút tiền

}
